services:
  - type: web
    name: infinite-locus
    runtime: node
    rootDir: ./
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production